#!/bin/bash

cat >/etc/zabbix/zabbix_agentd.conf <<EOF;
PidFile=/var/run/zabbix/zabbix_agentd.pid
LogFile=/var/log/zabbix/zabbix_agentd.log
LogFileSize=0
Server=172.16.1.21
ServerActive=172.16.1.21
Hostname=`hostname`
Include=/etc/zabbix/zabbix_agentd.d/
EOF
echo "configuration successful."

