#!/bin/bash

cat >/etc/zabbix/zabbix_agentd.conf <<EOF;
PidFile=/var/run/zabbix/zabbix_agentd.pid
LogFile=/var/log/zabbix/zabbix_agentd.log
LogFileSize=0
Server=zabbix.suzutan.jp
ServerActive=zabbix.suzutan.jp
Hostname=`hostname`
Include=/etc/zabbix/zabbix_agentd.d/
EOF
echo "configuration successful."

