#!/bin/bash

cd `dirname $0`

APP_NAME=`pwd | awk -F "/" '{print $NF}'`
VERSION=${1:-3.6.0}

if type pyenv 1>/dev/null 2>/dev/null ; then
    pyenv install -s $VERSION
    pyenv virtualenv $VERSION $APP_NAME
    pyenv local $APP_NAME
    pip install --upgrade pip setuptools
    pip install -r requirements.txt
else
    echo "pyenv not installed." 1>&2
    exit 1
fi

