#!/bin/bash -ue


cat > /etc/yum.repos.d/nginx.repo << 'EOL'
[hnakamur-apache-traffic-server-7]
name=Copr repo for apache-traffic-server-7 owned by hnakamur
baseurl=https://copr-be.cloud.fedoraproject.org/results/hnakamur/apache-traffic-server-7/epel-7-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/hnakamur/apache-traffic-server-7/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
EOL

